/* ===================================================================
   TAMBAYAN CAWAG — SUPABASE ORDERS MODULE
   -------------------------------------------------------------------
   Tables: orders (full record, admin-only), order_status (public-safe
   summary, no name/phone/email — see supabase/schema.sql's design
   notes for why these are split).

   Implements the exact same window.TCOrders interface the rest of
   this project already calls (subscribeOrders, createOrder,
   updateOrderStatus, getOrderByReservationNumber).

   PRICE TRUST: this module never accepts a price from the caller as
   the source of truth. createOrder() expects orderData.items to
   already be re-priced against the live menu cache — see
   reverifyCartAgainstMenu() in reservation.js, called by main.js
   before this module is invoked (unchanged by this migration). The
   create_order() Postgres function (supabase/schema.sql) adds a
   second layer, rejecting malformed writes (empty items, negative
   subtotal, missing required fields) — see that file's comments for
   why full server-side price recalculation is a documented next step
   rather than included here.

   ORDER NUMBERS: generated by generate_order_number(), a Postgres
   sequence wrapped in a SECURITY DEFINER function, so two simultaneous
   orders can never collide.
=================================================================== */

import { supabase, SUPABASE_READY, notReadyMessage } from "./supabase-config.js";

/**
 * Creates a pre-order/reservation via the create_order() RPC, which
 * validates and writes both the full record and its public-safe
 * summary atomically. Throws on any Supabase failure; callers must
 * catch and show a friendly error rather than assuming success.
 */
async function createOrder(orderData) {
  if (!SUPABASE_READY) {
    throw new Error("We're currently unable to submit your pre-order. Please check your connection and try again.");
  }

  const { data, error } = await supabase.rpc("create_order", {
    p_customer_name: orderData.customerName,
    p_customer_phone: orderData.phone,
    p_customer_email: orderData.email || "",
    p_order_date: orderData.date,
    p_order_time: orderData.time,
    p_guests: Number(orderData.guests),
    p_seating: orderData.seating,
    p_items: orderData.items,
    p_subtotal: orderData.subtotal,
    p_notes: orderData.specialInstructions || ""
  });

  if (error) {
    console.error("create_order RPC failed:", error);
    throw new Error("We're currently unable to submit your pre-order. Please check your connection and try again.");
  }

  return { reservationNumber: data, status: "pending" };
}

/** Real-time subscription for the admin dashboard. Fires on every add/update. */
function subscribeOrders(onChange, onError) {
  if (!SUPABASE_READY) {
    if (onError) onError(new Error(notReadyMessage()));
    return () => {};
  }

  let latest = [];

  async function refresh() {
    const { data, error } = await supabase
      .from("orders")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(200);
    if (error) {
      console.error("orders fetch error:", error);
      if (onError) onError(error);
      return;
    }
    const mapped = (data || []).map(mapOrderRow);
    const previousIds = new Set(latest.map((o) => o.id));
    const addedIds = mapped.filter((o) => !previousIds.has(o.id)).map((o) => o.id);
    latest = mapped;
    onChange(mapped, addedIds);
  }

  refresh();

  const channel = supabase
    .channel("tc-orders-changes")
    .on("postgres_changes", { event: "*", schema: "public", table: "orders" }, refresh)
    .subscribe();

  return () => supabase.removeChannel(channel);
}

function mapOrderRow(row) {
  return {
    id: row.id,
    reservationNumber: row.order_number,
    customerName: row.customer_name,
    phone: row.customer_phone,
    email: row.customer_email || "",
    date: row.order_date,
    time: typeof row.order_time === "string" ? row.order_time.slice(0, 5) : row.order_time,
    guests: row.guests,
    seating: row.seating,
    specialInstructions: row.notes || "",
    items: row.items,
    subtotal: Number(row.subtotal),
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

/** Admin-only. Updates status on both the full record and its public summary via RPC.
 *  `orderId` (the row's UUID) is accepted for interface parity with the call
 *  site but isn't needed here — update_order_status() looks the row up by
 *  order_number, which every caller already has on hand. */
async function updateOrderStatus(orderId, reservationNumber, status) {
  if (!SUPABASE_READY) throw new Error(notReadyMessage());
  const { error } = await supabase.rpc("update_order_status", {
    p_order_number: reservationNumber,
    p_status: status
  });
  if (error) throw error;
}

/** Customer-facing lookup by reservation number, via the get_order_status()
 *  RPC — an exact-key lookup that only ever touches the public-safe
 *  order_status table (no name/phone/email exposed). */
async function getOrderByReservationNumber(reservationNumber) {
  if (!SUPABASE_READY) throw new Error(notReadyMessage());
  const { data, error } = await supabase.rpc("get_order_status", { p_order_number: reservationNumber });
  if (error) throw error;
  if (!data || data.length === 0) return null;
  const row = data[0];
  return {
    reservationNumber: row.order_number,
    date: row.order_date,
    time: typeof row.order_time === "string" ? row.order_time.slice(0, 5) : row.order_time,
    guests: row.guests,
    items: row.items,
    subtotal: Number(row.subtotal),
    status: row.status
  };
}

const TCOrders = {
  createOrder,
  subscribeOrders,
  updateOrderStatus,
  getOrderByReservationNumber
};

window.TCOrders = TCOrders;
export default TCOrders;
